"""add domain Inventory persistence

Revision ID: 61ed70a2ef14
Revises: 5a8435d5e293
Create Date: 2025-10-19 18:07:01.237645

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '61ed70a2ef14'
down_revision: Union[str, Sequence[str], None] = '5a8435d5e293'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('domains', sa.Column('state_code', sa.Integer(), nullable=True))
    op.add_column('domains', sa.Column('persistent', sa.Boolean(), nullable=True))
    op.add_column('domains', sa.Column('metrics', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False))
    op.add_column('domains', sa.Column('guest_agent_ips', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('domains', 'guest_agent_ips')
    op.drop_column('domains', 'metrics')
    op.drop_column('domains', 'persistent')
    op.drop_column('domains', 'state_code')
    # ### end Alembic commands ###

